/*
 * Customer API
 * This is the customer API. It provides restful API for customer data
 *
 * OpenAPI spec version: 1.0.0
 * Contact: partha.roy-chowdhury@capgemini.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.api;

import io.swagger.client.model.Customer;
import org.junit.Test;
import org.junit.Ignore;


import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for DefaultApi
 */
@Ignore
public class DefaultApiTest {

    private final DefaultApi api = new DefaultApi();

    
    /**
     * adds a new customer
     *
     * Add a new customer to the System
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void addCustomerTest() throws Exception {
        Customer body = null;
        Integer response = api.addCustomer(body);

        // TODO: test validations
    }
    
    /**
     * Delete existing customer
     *
     * Deletes existing customer from system
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void deleteCustomerTest() throws Exception {
        Integer customerId = null;
        Customer response = api.deleteCustomer(customerId);

        // TODO: test validations
    }
    
    /**
     * reads a customer data
     *
     * This operation uses customer id to identify in a query string
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void getCustomerTest() throws Exception {
        Integer customerId = null;
        Customer response = api.getCustomer(customerId);

        // TODO: test validations
    }
    
    /**
     * update existing customer
     *
     * Updates an existing customer in system
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void updateCustomerTest() throws Exception {
        Customer body = null;
        Integer customerId = null;
        api.updateCustomer(body, customerId);

        // TODO: test validations
    }
    
}
